name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DOCKER_COMPOSE_VERSION: 1.23.2
  GIT_SHA: ${{ github.sha }}

jobs:
  test_and_analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/${{ env.DOCKER_COMPOSE_VERSION }}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: List directory contents
        run: |
          echo "Listing contents of the current directory:"
          ls -al
          echo "Listing contents of subdirectories:"
          find . -type d

      - name: Run Unit Tests
        run: |
          cd Chapter04
          docker-compose build db
          docker-compose build test-postgresql
          docker-compose run test-postgresql

      - name: Run Static Analysis
        run: |
          cd Chapter04
          docker-compose build static-analysis
          docker-compose run static-analysis

