name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DOCKER_COMPOSE_VERSION: 1.23.2
  GIT_SHA: ${{ github.sha }}

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variables
        run: |
          echo "DOCKER_COMPOSE_VERSION: $DOCKER_COMPOSE_VERSION"
          echo "GIT_SHA: $GIT_SHA"

